### ISSUE TITLE
[BUILD] Trying on ubuntu 18.04

### ISSUE THREAD

**Issue by tyoc213** [facebookresearch/TensorComprehensions#614]
Tensor Comprehensions Github Issues Guidelines
----------------------------------------------

When submitting a bug report, please include the following information (where relevant):
- OS: Ubuntu  18.04
- How you installed TC (docker, conda, source): anaconda3/envs/tc_build/lib/python3.6 (as  https://facebookresearch.github.io/TensorComprehensions/installation.html#conda-from-scratch-first-time-configuration)
- Python version: 3.6
- CUDA/cuDNN version: libcudnn7-dev_7.5.0.56-1+cuda10
- Conda version (if using conda): 4.6.8
- GCC/GXX version (if compiling from source): cc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)
- LLVM/Tapir git hash used (if compiling from source): llvmlite                  0.27.0           py37hd408876_0

- Commit hash of our repo and submodules (if compiling from source): 03ecae01557a5e4a196dd858b10a57b224df52cd

In addition, including the following information will also be very helpful for us to diagnose the problem:

```
$ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensor_comprehensions as tc
>>> import torch
>>> lang = """
... def tensordot(float(N, C1, C2, H, W) I0, float(N, C2, C3, H, W) I1) -> (O) {
...     O(n, c1, c3, h, w) +=! I0(n, c1, c2, h, w) * I1(n, c2, c3, h, w)
... }
... """
>>> N, C1, C2, C3, H, W = 32, 512, 8, 2, 28, 28
>>> tensordot = tc.define(lang, name="tensordot")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: define() got an unexpected keyword argument 'name'
>>> I0, I1 = torch.randn(N, C1, C2, H, W).cuda(), torch.randn(N, C2, C3, H, W).cuda()

/home/tyoc213/anaconda3/envs/tc_build/lib/python3.6/site-packages/torch/cuda/__init__.py:114: UserWarning: 
    Found GPU0 GeForce RTX 2080 which requires CUDA_VERSION >= 9000 for
     optimal performance and fast startup time, but your PyTorch was compiled
     with CUDA_VERSION 8000. Please install the correct PyTorch binary
     using instructions from http://pytorch.org
    
  warnings.warn(incorrect_binary_warn % (d, name, 9000, CUDA_VERSION))
>>> best_options = tensordot.autotune(I0, I1, cache=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'tensordot' is not defined
>>> out = tensordot(I0, I1, options=best_options)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'tensordot' is not defined
>>> 
```

So, I cant install from source correctly.

By the way, what is the state of this project, it seems like there are a lot of pull request and 8 or 9 months of zero work made in this public repo.

**Comment by ghostplant** [comment]
Same problem, is there a docker image version provided for cuda?
